package tui

import (
	"time"

	"github.com/gnanam1990/zero-review/internal/review"
)

// MockSession returns a realistic review session for demos and tests.
func MockSession() *review.ReviewSession {
	return &review.ReviewSession{
		PR: review.PRMetadata{
			Owner:        "example",
			Repo:         "payments",
			Number:       123,
			Title:        "feat: add payment webhook handler",
			Body:         "This PR introduces a new webhook handler for payment events.",
			Author:       "devuser",
			SourceBranch: "feature/payments",
			TargetBranch: "main",
			ChangedFiles: 12,
			Additions:    842,
			Deletions:    210,
			URL:          "https://github.com/example/payments/pull/123",
		},
		Findings: []review.Finding{
			{
				ID:               "F001",
				Title:            "Verify signature before state mutation",
				Severity:         review.SeverityHigh,
				Category:         review.CategorySecurity,
				Confidence:       94,
				FilePath:         "webhook/handler.go",
				LineStart:        88,
				LineEnd:          90,
				DiffSide:         "RIGHT",
				Explanation:      "The handler updates payment state before verifying the webhook signature. A forged request may mutate payment status.",
				SuggestedComment: "Signature verification should happen before payment state mutation. Please move verifySignature before updatePaymentStatus.",
				SuggestedFix:     "Read the request body, verify the signature, then update the payment state.",
				Evidence:         "updatePaymentStatus is called before verifySignature.",
				Status:           review.FindingStatusPending,
			},
			{
				ID:               "F002",
				Title:            "Missing invalid signature test",
				Severity:         review.SeverityMedium,
				Category:         review.CategoryTest,
				Confidence:       89,
				FilePath:         "webhook/handler_test.go",
				LineStart:        44,
				LineEnd:          44,
				DiffSide:         "RIGHT",
				Explanation:      "Tests cover success cases but do not exercise invalid or missing signatures.",
				SuggestedComment: "Please add a test for invalid webhook signatures to ensure the handler rejects them.",
				SuggestedFix:     "Add TestHandleWebhook_InvalidSignature.",
				Evidence:         "Only success-path tests exist in handler_test.go.",
				Status:           review.FindingStatusPending,
			},
			{
				ID:               "F003",
				Title:            "Missing replay attack test",
				Severity:         review.SeverityMedium,
				Category:         review.CategoryTest,
				Confidence:       85,
				FilePath:         "webhook/handler_test.go",
				LineStart:        71,
				LineEnd:          71,
				DiffSide:         "RIGHT",
				Explanation:      "Replay attacks are not covered by the test suite. Idempotency keys should be validated.",
				SuggestedComment: "Consider adding a replay test using the event idempotency key.",
				SuggestedFix:     "Store seen event IDs and reject duplicates.",
				Status:           review.FindingStatusPending,
			},
			{
				ID:               "F004",
				Title:            "Duplicate validation logic",
				Severity:         review.SeverityLow,
				Category:         review.CategoryMaintainability,
				Confidence:       71,
				FilePath:         "config.go",
				LineStart:        21,
				LineEnd:          21,
				DiffSide:         "RIGHT",
				Explanation:      "Validation for the webhook secret is repeated in two places.",
				SuggestedComment: "Extract the secret validation into a shared helper to avoid duplication.",
				SuggestedFix:     "func validateSecret(s string) error { ... }",
				Status:           review.FindingStatusPending,
			},
			{
				ID:               "F005",
				Title:            "Raw body read without limit",
				Severity:         review.SeverityMedium,
				Category:         review.CategoryBug,
				Confidence:       82,
				FilePath:         "webhook/handler.go",
				LineStart:        83,
				LineEnd:          83,
				DiffSide:         "RIGHT",
				Explanation:      "io.ReadAll can exhaust memory if a large request body is sent.",
				SuggestedComment: "Use io.LimitReader or set a max body size before reading the webhook payload.",
				SuggestedFix:     "io.LimitReader(r.Body, maxBodySize)",
				Status:           review.FindingStatusPending,
			},
			{
				ID:               "F006",
				Title:            "Error response leaks internal details",
				Severity:         review.SeverityLow,
				Category:         review.CategorySecurity,
				Confidence:       76,
				FilePath:         "webhook/handler.go",
				LineStart:        95,
				LineEnd:          95,
				DiffSide:         "RIGHT",
				Explanation:      "Returning raw verification errors may reveal implementation details to attackers.",
				SuggestedComment: "Return a generic error message to the caller and log details internally.",
				SuggestedFix:     "http.Error(w, \"invalid request\", http.StatusBadRequest)",
				Status:           review.FindingStatusPending,
			},
			{
				ID:               "F007",
				Title:            "Add package-level doc comment",
				Severity:         review.SeverityInfo,
				Category:         review.CategoryDocs,
				Confidence:       95,
				FilePath:         "webhook/handler.go",
				LineStart:        1,
				LineEnd:          1,
				DiffSide:         "RIGHT",
				Explanation:      "The webhook package lacks a doc comment describing its purpose.",
				SuggestedComment: "Consider adding a package doc comment.",
				Status:           review.FindingStatusPending,
			},
		},
		Summary:   "This PR adds webhook payment handling. The main risk is that state mutation appears to happen before signature verification in one path. Tests cover success cases but miss replay and invalid signature cases.",
		RiskScore: 0,
		Provider:  "fake",
		Model:     "demo",
		Mode:      "balanced",
		Posted:    false,
		CreatedAt: time.Now().UTC(),
	}
}
